### ISSUE TITLE
Emulator start timed out.

### ISSUE THREAD

**Issue by Rajesh-Ganesh** [filipesimoes/j3270#3]
Using the code and see issue while starting Emulator as following:

java.util.concurrent.TimeoutException: Emulator start timed out.
	at com.github.filipesimoes.j3270.Emulator.waitForEmulator(Emulator.java:67)
	at com.github.filipesimoes.j3270.Emulator.start(Emulator.java:53)
	at com.broadridge.emulator.MainFrame.main(MainFrame.java:20)

Code:

 try (Emulator emulator = new Emulator()) {
            emulator.setVisible(true);
            emulator.setNvt(true);
            emulator.start();

            emulator.waitField(10);
            emulator.disconnect();
        } catch (IOException | TimeoutException e) {
            e.printStackTrace();
        }

Can you please help?

**Comment by filipesimoes** [comment]
Have you checked if the emulator is installed and/or at your system path?

[x3270 emulator download path](https://x3270.miraheze.org/wiki/Downloads)

**Comment by Rajesh-Ganesh** [comment]
Thank you for the reply.

Have installed and it's also set in the PATH and even see the wc3270.exe on the Task Manager being started, but it's unable to proceed further. The py3270 works fine on the same host and it's able to start the emulator and execute commands.

Was working on code to check if the reason is due to Proxy and was able to get the Socket connection with the below code change(Not sure if this is the right way) to TerminalCommander.waitForSocket(), but now it fails while doing emulator.connect()

      SocketAddress proxyAddr = new InetSocketAddress("proxy.address.com", 8080);
      Proxy proxy = new Proxy(Proxy.Type.HTTP, proxyAddr);
      socket = new Socket(proxy);
      socket.connect(new InetSocketAddress("localhost", scriptPort), 50);
      socket.setKeepAlive(true);

Current Issue with Changes:

Exception in thread "main" java.lang.NullPointerException
	at com.github.filipesimoes.j3270.command.AbstractCommand.processResult(AbstractCommand.java:44)
	at com.github.filipesimoes.j3270.command.AbstractCommand.execute(AbstractCommand.java:25)
	at com.github.filipesimoes.j3270.TerminalCommander.execute(TerminalCommander.java:25)
	at com.github.filipesimoes.j3270.Emulator.execute(Emulator.java:189)
	at com.github.filipesimoes.j3270.Emulator.connect(Emulator.java:173)
	at com.github.filipesimoes.j3270.Mainframe.main(Mainframe.java:13)

Tried to check what's happening with socket.getInputStream() with below code and i always return with -1

InputStream inputStream = socket.getInputStream();
    while (true) {
      byte b[] = new byte[100];
      int i = inputStream.read();
      if (i == -1)
        break;
      System.out.print(new String(b, 0, i));
    }

Thanks for the help

**Comment by filipesimoes** [comment]
This proxy code won't work because you're adding a proxy to the emulator local script port.
It is a connection used to communicate with the emulator process through localhost:[scriptPort]. It is not here that a proxy would be necessary.
I've never used it behind a proxy, but I think if it is the case it would be necessary to add a new parameter to Emulator3270Runner and at Emulator3270Runner.buildArgs add this [option](https://x3270.miraheze.org/wiki/Proxy_resource).
You can try this hard coded and submit a PR with the appropriate parameters if you like.

**Comment by Rajesh-Ganesh** [comment]
The args didn't help. (-proxy http:username:pwd@proxyIP). Still throws exception while connecting to Socket:

java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:75)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:476)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:218)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:200)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:162)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:394)
	at java.net.Socket.connect(Socket.java:606)
	at java.net.Socket.connect(Socket.java:555)
	at java.net.Socket.<init>(Socket.java:451)
	at java.net.Socket.<init>(Socket.java:228)
	at com.github.filipesimoes.j3270.TerminalCommander.waitForSocket(TerminalCommander.java:72)
	at com.github.filipesimoes.j3270.TerminalCommander.connect(TerminalCommander.java:30)
	at com.github.filipesimoes.j3270.Emulator.start(Emulator.java:57)
	at com.github.filipesimoes.j3270.Mainframe.main(Mainframe.java:12)
